#!/bin/bash

echo Deploy attempted at: `date` >> log/deploy.log
if [[ -d /srv/http/thesportspost ]]; then
  cd /srv/http/thesportspost
  if [[ ! -f tmp/deploy.lock ]]; then
    touch tmp/deploy.lock
    git pull
    RAILS_ENV=production rake db:migrate
    RAILS_ENV=production rake assets:precompile
    thin restart -O -C config/thin.yml
    echo Deploy finished at: `date` >> log/deploy.log
    rm tmp/deploy.lock
  else
    echo Deploy failed at: `date` >> log/deploy.log
  fi
fi

